# I-it's not like I spent ten minutes recalculating these coordinates for you! 😤
background {
    monitor =
    color = rgb(000000)
}

# The OS Label
label {
    monitor =
    text = Siin ina uumi Bibbulim.
    color = rgb(200, 200, 200)
    font_size = 18
    font_family = monospace
    position = 5, -10
    halign = left
    valign = top
}

# The Kernel Label (Using a run-once command!)
label {
    monitor =
    text = cmd[update:0] echo "Kernel: $(uname -r)"
    color = rgb(200, 200, 200)
    font_size = 18
    font_family = monospace
    position = 10, -30
    halign = left
    valign = top
}

# The Login Label
label {
    monitor =
    text = bibbul login: qayiran
    color = rgb(200, 200, 200)
    font_size = 18
    font_family = monospace
    position = 10, -60
    halign = left
    valign = top
}

# The Password Label
label {
    monitor =
    text = Password:
    color = rgb(200, 200, 200)
    font_size = 18
    font_family = monospace
    position = 10, -80
    halign = left
    valign = top
}

# The Actually Invisible Password Input
input-field {
    monitor =
    size = 250, 20
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = false
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    font_family = monospace
    placeholder_text = <span font_family="monospace" foreground="##c8c8c8">_</span>
    
    # 🛑 I AM CHANGING THIS TO TRUE FOR YOU! 
    hide_input = true 
    
    position = 110, -80
    halign = left
    valign = top
}
