--ozone-platform=wayland
--ignore-gpu-blocklist
--enable-features=VaapiVideoDecoder,VaapiVideoEncoder,UseOzonePlatform
--disable-features=UseDav1dVideoDecoder,Vulkan,CanvasOopRasterization,HardwareOverlays,GpuRasterization,ZeroCopy,OneCopy,DrDc
--use-gl=angle
--use-angle=gl
--disable-gpu-rasterization
--disable-zero-copy
